# Generated by Django 3.1.6 on 2020-04-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Выполнено?'),
        ),
    ]
